_DF_ = "/"

_BINANCE_MODULE_DIR_NAME_ = "Binance"
_KEYS_FILE_NAME_ = ".keys"
_KEYS_FILE_PATH_ = _BINANCE_MODULE_DIR_NAME_ + _DF_ + _KEYS_FILE_NAME_

_ENTRY_TYPE_ = 0
_LOSE_TYPE_ = 1
_PROFIT_TYPE_ = 2

_INIT_STATE_ = 0
_WAITING_STATE_ = 1
_OPEN_STATE_ = 2
_FILLED_STATE_ = 3
_CANCELED_STATE_ = 4
_DISABLED_STATE_ = 5




_TRANSACTION_TABLE_NAME_ = "Transaction"
_SYMBOL_COL_NAME_ = "symbol"

_ORDER_TABLE_NAME_ = "Binance_Order"
_TRANSACTION_ID_COL_NAME_ = "transaction_id"
_PRICE_COL_NAME_ = "price"
_TYPE_COL_NAME_ = "type"
_STATE_COL_NAME_ = "state"

_DATES_TABLE_NAME_ = "Dates"
_ORDER_ID_COL_NAME_ = "order_id"
_INIT_DATE_COL_NAME_ = "init_date"